from flask import Flask,request,jsonify
import pickle
import numpy as np

model = pickle.load(open('bangluru_home_price_prediction.pickle','rb'))
columns = ['bhk',
'total_sqft',
'bath',
'1st Block Jayanagar',
'1st Block Koramangala',
'1st Phase JP Nagar',
'2nd Phase Judicial Layout',
'2nd Stage Nagarbhavi',
'5th Block Hbr Layout',
'5th Phase JP Nagar',
'6th Phase JP Nagar',
'7th Phase JP Nagar',
'8th Phase JP Nagar',
'9th Phase JP Nagar',
'AECS Layout',
'Abbigere',
'Akshaya Nagar',
'Ambalipura',
'Ambedkar Nagar',
'Amruthahalli',
'Anandapura',
'Ananth Nagar',
'Anekal',
'Anjanapura',
'Ardendale',
'Arekere',
'Attibele',
'BEML Layout',
'BTM 1st Stage',
'BTM 2nd Stage',
'BTM Layout',
'Babusapalaya',
'Badavala Nagar',
'Balagere',
'Banashankari',
'Banashankari Stage II',
'Banashankari Stage III',
'Banashankari Stage V',
'Banashankari Stage VI',
'Banaswadi',
'Banjara Layout',
'Bannerghatta',
'Bannerghatta Road',
'Basapura',
'Basavangudi',
'Basaveshwara Nagar',
'Battarahalli',
'Begur',
'Begur Road',
'Bellandur',
'Benson Town',
'Bharathi Nagar',
'Bhoganhalli',
'Billekahalli',
'Binny Pete',
'Bisuvanahalli',
'Bommanahalli',
'Bommasandra',
'Bommasandra Industrial Area',
'Bommenahalli',
'Brookefield',
'Budigere',
'CV Raman Nagar',
'Chamrajpet',
'Chandapura',
'Channasandra',
'Chikka Tirupathi',
'Chikkabanavar',
'Chikkalasandra',
'Choodasandra',
'Cooke Town',
'Cox Town',
'Cunningham Road',
'Dairy Circle',
'Dasanapura',
'Dasarahalli',
'Devanahalli',
'Devarachikkanahalli',
'Dodda Nekkundi',
'Doddaballapur',
'Doddakallasandra',
'Doddathoguru',
'Dodsworth Layout',
'Domlur',
'Dommasandra',
'EPIP Zone',
'Electronic City',
'Electronic City Phase II',
'Electronics City Phase 1',
'Frazer Town',
'GM Palaya',
'Ganga Nagar',
'Garudachar Palya',
'Giri Nagar',
'Gollarapalya Hosahalli',
'Gottigere',
'Green Glen Layout',
'Gubbalala',
'Gunjur',
'Gunjur Palya',
'HAL 2nd Stage',
'HBR Layout',
'HRBR Layout',
'HSR Layout',
'Haralur Road',
'Harlur',
'Hebbal',
'Hebbal Kempapura',
'Hegde Nagar',
'Hennur',
'Hennur Road',
'Hoodi',
'Horamavu Agara',
'Horamavu Banaswadi',
'Hormavu',
'Hosa Road',
'Hosakerehalli',
'Hoskote',
'Hosur Road',
'Hulimavu',
'ISRO Layout',
'ITPL',
'Iblur Village',
'Indira Nagar',
'JP Nagar',
'Jakkur',
'Jalahalli',
'Jalahalli East',
'Jigani',
'Judicial Layout',
'KR Puram',
'Kadubeesanahalli',
'Kadugodi',
'Kaggadasapura',
'Kaggalipura',
'Kaikondrahalli',
'Kalena Agrahara',
'Kalkere',
'Kalyan nagar',
'Kambipura',
'Kammanahalli',
'Kammasandra',
'Kanakapura',
'Kanakpura Road',
'Kannamangala',
'Karuna Nagar',
'Kasavanhalli',
'Kasturi Nagar',
'Kathriguppe',
'Kaval Byrasandra',
'Kenchenahalli',
'Kengeri',
'Kengeri Satellite Town',
'Kereguddadahalli',
'Kodichikkanahalli',
'Kodigehaali',
'Kodigehalli',
'Kodihalli',
'Kogilu',
'Konanakunte',
'Koramangala',
'Kothannur',
'Kothanur',
'Kudlu',
'Kudlu Gate',
'Kumaraswami Layout',
'Kundalahalli',
'LB Shastri Nagar',
'Laggere',
'Lakshminarayana Pura',
'Lingadheeranahalli',
'Magadi Road',
'Mahadevpura',
'Mahalakshmi Layout',
'Mallasandra',
'Malleshpalya',
'Malleshwaram',
'Marathahalli',
'Margondanahalli',
'Marsur',
'Mico Layout',
'Munnekollal',
'Murugeshpalya',
'Mysore Road',
'NGR Layout',
'NRI Layout',
'Nagadevanahalli',
'Naganathapura',
'Nagappa Reddy Layout',
'Nagarbhavi',
'Nagasandra',
'Nagavara',
'Nagavarapalya',
'Narayanapura',
'Neeladri Nagar',
'Nehru Nagar',
'OMBR Layout',
'Old Airport Road',
'Old Madras Road',
'Padmanabhanagar',
'Pai Layout',
'Panathur',
'Parappana Agrahara',
'Pattandur Agrahara',
'Poorna Pragna Layout',
'Prithvi Layout',
'R.T. Nagar',
'Rachenahalli',
'Raja Rajeshwari Nagar',
'Rajaji Nagar',
'Rajiv Nagar',
'Ramagondanahalli',
'Ramamurthy Nagar',
'Rayasandra',
'Sadashiva Nagar',
'Sahakara Nagar',
'Sanjay nagar',
'Sarakki Nagar',
'Sarjapur',
'Sarjapur  Road',
'Sarjapura - Attibele Road',
'Sector 2 HSR Layout',
'Sector 7 HSR Layout',
'Seegehalli',
'Shampura',
'Shivaji Nagar',
'Singasandra',
'Somasundara Palya',
'Sompura',
'Sonnenahalli',
'Subramanyapura',
'Sultan Palaya',
'TC Palaya',
'Talaghattapura',
'Thanisandra',
'Thigalarapalya',
'Thubarahalli',
'Thyagaraja Nagar',
'Tindlu',
'Tumkur Road',
'Ulsoor',
'Uttarahalli',
'Varthur',
'Varthur Road',
'Vasanthapura',
'Vidyaranyapura',
'Vijayanagar',
'Vishveshwarya Layout',
'Vishwapriya Layout',
'Whitefield',
'Yelachenahalli',
'Yelahanka',
'Yelahanka New Town',
'Yelenahalli',
'Yeshwanthpur',
'other']

app = Flask(__name__)

@app.route('/')
def home():
    return "Hello world"

@app.route('/predict',methods=['POST'])
def predict():
    bhk = request.form.get('bhk')
    totalsqft = request.form.get('totalsqft')
    bath = request.form.get('bath')
    location = request.form.get('location')

    result = predict_price(bhk,totalsqft,bath,location,columns)
    return jsonify({'price':str(result)})

def predict_price(bhk,totalsqft,bath,location,columnss):
    
    loc_index = np.where(location in columnss,columns.index(location),0)
    print(loc_index)

    
    x = np.zeros(len(columnss))
    x[0] = bhk
    x[1] = totalsqft
    x[2] = bath
    x[loc_index] = 1
    
    return model.predict([x])[0]

if __name__ == '__main__':
    app.run(debug=True)



